spring.application.name=admin

server.port=8086

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://comprehensive-project.cj06aomcgfqr.ap-northeast-2.rds.amazonaws.com/comprehensive_project

spring.datasource.username=admin
spring.datasource.password=Eureka!#%!#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=5

#??? ??
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=